#!/bin/bash

RTORRENT_EXEC="rtorrent -n -o try_import=/etc/rtorrent.rc,system.daemon.set=true"
RTORRENT_LOG="/data/local/log/rtorrent"

mv $RTORRENT_LOG/*.log.* $RTORRENT_LOG/old
nohup $RTORRENT_EXEC > $RTORRENT_LOG/daemon.log &

sleep 1
