#!/bin/bash

RTORRENT_EXEC="rtorrent -n -o try_import=/etc/rtorrent.rc,system.daemon.set=true"
RTORRENT_LOG="/data/local/log/rtorrent"

LOG_DATE=`date -u '+%F_%H-%M-%S'`

for i in ${RTORRENT_LOG}/*.log; do
    mv ${i} ${i/\/rtorrent\//\/rtorrent\/old\/}.${LOG_DATE}
done

if [ "$DEBUG" == "yes" ]; then
    gdb --args ${RTORRENT_EXEC}
else
    nohup ${RTORRENT_EXEC} > ${RTORRENT_LOG}/daemon.log &
fi

sleep 1
