#!/bin/bash

RTORRENT_LOCKFILE="/data/local/session/rtorrent.lock"

if [ ! -e $RTORRENT_LOCKFILE ]; then
    exit 0
fi

RTORRENT_PID=`sed -n 's/^[^:]*:+\([0-9].*\)$/\1/p' $RTORRENT_LOCKFILE`

kill $RTORRENT_PID || true
