#!/bin/bash

# TODO: Make it return a string; 'not found', 'zero length', 'blank', 'not completed' and 'completed'.

LOCAL_PATH="/data/torrents"
SHARED_PATH="/data/shared/torrents"

if [ ! -f "${SHARED_PATH}/$1" ]; then
    echo "invalid"
    exit -1
fi

if [ ! -f "${LOCAL_PATH}/$1" ]; then
    echo "missing"
    exit -1
fi

if [ ! -s "${LOCAL_PATH}/$1" ]; then
    echo "truncated"
    exit -1
fi

if cmp -s "${LOCAL_PATH}/$1" "${SHARED_PATH}/$1"; then
    echo "complete"
else
    echo "incomplete"
fi
