#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

echo "running bind_port_simple"

clean_all

# Tests that ipv4 and ipv6 are bound properly.
"${SCRIPT_DIR}/config-set-port-range" node2 15500 15600
"${SCRIPT_DIR}/config-set-port-range" node3 16500 16600

"${SCRIPT_DIR}/config-set-block-connect" node2
"${SCRIPT_DIR}/config-set-block-connect" node3

setup if1p1_if2p1

verify_completed   node2 test_h4_if1 "incoming http4 tracker with v4only"
verify_completed   node2 test_u4_if1 "incoming udp4  tracker with v4only"
verify_incompleted node2 test_h6_if1 "incoming http6 tracker with v4only"
verify_incompleted node2 test_u6_if1 "incoming udp6  tracker with v4only"
verify_incompleted node2 test_h4_if2 "incoming http4 tracker with v4only, port blocked"
verify_incompleted node2 test_u4_if2 "incoming udp4  tracker with v4only, port blocked"
verify_incompleted node2 test_h6_if2 "incoming http6 tracker with v4only, port blocked"
verify_incompleted node2 test_u6_if2 "incoming udp6  tracker with v4only, port blocked"

verify_incompleted node3 test_h4_if1 "incoming http4 tracker with v6only"
verify_incompleted node3 test_u4_if1 "incoming udp4  tracker with v6only"
verify_completed   node3 test_h6_if1 "incoming http6 tracker with v6only"
verify_completed   node3 test_u6_if1 "incoming udp6  tracker with v6only"
verify_incompleted node3 test_h4_if2 "incoming http4 tracker with v6only, port blocked"
verify_incompleted node3 test_u4_if2 "incoming udp4  tracker with v6only, port blocked"
verify_incompleted node3 test_h6_if2 "incoming http6 tracker with v6only, port blocked"
verify_incompleted node3 test_u6_if2 "incoming udp6  tracker with v6only, port blocked"

exit_test
