#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

# TODO: Rename to outgoing.
echo "running bind_separate_v4v6"

clean_all

"${SCRIPT_DIR}/config-set-block-connect" node1

NODES="node2 node3" "${SCRIPT_DIR}/config-use-bind-address-4"

setup pair_v4v6

# TODO: Need to also add test for incoming, requires a new clean test.

# node2 tests outgoing bind v4 on if1, v6 on if2
# - v4 should work on if1
# - v6 should work on if2
# - v6 should not work on if1
# - v4 should not work on if2

# TODO: What to test on node3?

# TODO: Add helper method that gives us some better output.

# When bind and v4only, v4 works and v6 does not work.
verify_completed   node2 test_h4_if1 "verifying it works with http4 tracker over ipv4"
verify_completed   node2 test_u4_if1 "verifying it works with udp4  tracker over ipv4"
verify_incompleted node2 test_h6_if1 "verifying it does not work with http6 tracker over ipv6"
verify_incompleted node2 test_u6_if1 "verifying it does not work with udp6  tracker over ipv6"

# When bind and v6only, v4 does not work and v6 works.
verify_incompleted node2 test_h4_if2 "verifying it does not work with http4 tracker over ipv4"
verify_incompleted node2 test_u4_if2 "verifying it does not work with udp4  tracker over ipv4"
verify_completed   node2 test_h6_if2 "verifying it works with http6 tracker over ipv6"
verify_completed   node2 test_u6_if2 "verifying it works with udp6  tracker over ipv6"


# verify_completed node3 test_h6_if1 "verifying it works with http6 tracker over ipv6"
# verify_completed node3 test_u6_if1 "verifying it works with udp6  tracker over ipv6"

# verify_incompleted node2 test_h6_if1 "verifying it does not work with http6 tracker over ipv4"
# verify_incompleted node2 test_u6_if1 "verifying it does not work with udp6  tracker over ipv4"
# verify_incompleted node3 test_h4_if1 "verifying it does not work with http4 tracker over ipv6"
# verify_incompleted node3 test_u4_if1 "verifying it does not work with udp4  tracker over ipv6"

exit_test
