#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

echo "running bind_port_simple"

clean_all

# Tests that ipv4 and ipv6 are bound properly.
"${SCRIPT_DIR}/config-set-port-range" node2 15500 15600
"${SCRIPT_DIR}/config-set-port-range" node3 16500 16600

"${SCRIPT_DIR}/config-set-block-connect" node2
"${SCRIPT_DIR}/config-set-block-connect" node3

POKE_SEED=yes setup pair

# Test:
# - with port bind ipv4+6 works
# - ipv4in6 an issue
# - add torrents over the other interface later

verify_completed   node2 test_h4_if1 "verifying it works with http4 tracker over ipv4"
verify_completed   node2 test_u4_if1 "verifying it works with udp4  tracker over ipv4"
verify_completed   node3 test_h6_if1 "verifying it works with http6 tracker over ipv6"
verify_completed   node3 test_u6_if1 "verifying it works with udp6  tracker over ipv6"

verify_incompleted node2 test_h4_if2 "verifying it does not work with http4 tracker over ipv4 when ports are blocked"
verify_incompleted node2 test_u4_if2 "verifying it does not work with udp4  tracker over ipv4 when ports are blocked"
verify_incompleted node3 test_h6_if2 "verifying it does not work with http6 tracker over ipv6 when ports are blocked"
verify_incompleted node3 test_u6_if2 "verifying it does not work with udp6  tracker over ipv6 when ports are blocked"

verify_incompleted node2 test_h6_if1 "verifying it does not work with http6 tracker when ipv6 is not available"
verify_incompleted node2 test_u6_if1 "verifying it does not work with udp6  tracker when ipv6 is not available"
verify_incompleted node3 test_h4_if1 "verifying it does not work with http4 tracker when ipv4 is not available"
verify_incompleted node3 test_u4_if1 "verifying it does not work with udp4  tracker when ipv4 is not available"

verify_incompleted node2 test_h6_if2 "verifying it does not work with http6 tracker when ipv6 is not available, blocked"
verify_incompleted node2 test_u6_if2 "verifying it does not work with udp6  tracker when ipv6 is not available, blocked"
verify_incompleted node3 test_h4_if2 "verifying it does not work with http4 tracker when ipv4 is not available, blocked"
verify_incompleted node3 test_u4_if2 "verifying it does not work with udp4  tracker when ipv4 is not available, blocked"

exit_test
