#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

echo "running bind_port_randomize"

clean_all

# node2: Verify sequential works; if1 fails, if2 works.
# node3: Verify randomized works; if1 works, if2 fails.

"${SCRIPT_DIR}/config-set-port-range" node2 15499 15900
"${SCRIPT_DIR}/config-set-port-range" node3 15499 15900

"${SCRIPT_DIR}/config-set-block-connect" node2
"${SCRIPT_DIR}/config-set-block-connect" node3

CREATE_IF2=yes CREATE_IPV6=no POKE_SEED=yes setup default_pair_v4

verify_incompleted node2 test_h4   "verifying sequential works with http4 tracker over ipv4"
verify_incompleted node2 test_u4   "verifying sequential works with udp4  tracker over ipv4"
verify_completed node2 test_h4_if2 "verifying sequential works with http4 tracker over ipv4"
verify_completed node2 test_u4_if2 "verifying sequential works with udp4  tracker over ipv4"

verify_completed node3 test_h4       "verifying randomized works with http4 tracker over ipv4"
verify_completed node3 test_u4       "verifying randomized works with udp4  tracker over ipv4"
verify_incompleted node3 test_h4_if2 "verifying randomized works with http4 tracker over ipv4"
verify_incompleted node3 test_u4_if2 "verifying randomized works with udp4  tracker over ipv4"

exit_test
