#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

echo "running bind_port_randomize_v4"

clean_all

# node2: Verify sequential works; if1 fails, if2 works.
# node3: Verify randomized works; if1 works, if2 fails.

# node2 will sequentially pick port 15499
# node3 will randomly pick a port between 15499-15900
"${SCRIPT_DIR}/config-set-port-range" node2 15499 15900
"${SCRIPT_DIR}/config-set-port-range" node3 15499 15900

"${SCRIPT_DIR}/config-set-block-connect" node2
"${SCRIPT_DIR}/config-set-block-connect" node3

"${SCRIPT_DIR}/config-disable-port-randomize" node2

POKE_SEED=yes setup pair_v4

verify_incompleted node2 test_h4_if1 "verifying sequential works with http4 tracker over ipv4"
verify_incompleted node2 test_u4_if1 "verifying sequential works with udp4  tracker over ipv4"
verify_completed   node2 test_h4_if2 "verifying sequential works with http4 tracker over ipv4"
verify_completed   node2 test_u4_if2 "verifying sequential works with udp4  tracker over ipv4"

verify_completed   node3 test_h4_if1 "verifying randomized works with http4 tracker over ipv4"
verify_completed   node3 test_u4_if1 "verifying randomized works with udp4  tracker over ipv4"
verify_incompleted node3 test_h4_if2 "verifying randomized works with http4 tracker over ipv4"
verify_incompleted node3 test_u4_if2 "verifying randomized works with udp4  tracker over ipv4"

exit_test
