#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

echo "running bind_port_randomize_v6"

clean_all

# node2: Verify sequential works; if1 fails, if2 works.
# node3: Verify randomized works; if1 works, if2 fails.

# node2 will sequentially pick port 16499
# node3 will randomly pick a port between 16499-16900
"${SCRIPT_DIR}/config-set-port-range" node2 16499 16900
"${SCRIPT_DIR}/config-set-port-range" node3 16499 16900

"${SCRIPT_DIR}/config-set-block-connect" node2
"${SCRIPT_DIR}/config-set-block-connect" node3

"${SCRIPT_DIR}/config-disable-port-randomize" node2

POKE_SEED=yes setup pair_v6

verify_incompleted node2 test_h6_if1 "verifying sequential works with http6 tracker over ipv6"
verify_incompleted node2 test_u6_if1 "verifying sequential works with udp6  tracker over ipv6"
verify_completed   node2 test_h6_if2 "verifying sequential works with http6 tracker over ipv6"
verify_completed   node2 test_u6_if2 "verifying sequential works with udp6  tracker over ipv6"

verify_completed   node3 test_h6_if1 "verifying randomized works with http6 tracker over ipv6"
verify_completed   node3 test_u6_if1 "verifying randomized works with udp6  tracker over ipv6"
verify_incompleted node3 test_h6_if2 "verifying randomized works with http6 tracker over ipv6"
verify_incompleted node3 test_u6_if2 "verifying randomized works with udp6  tracker over ipv6"

exit_test
