#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

echo "running bind_v6"

clean_all
NODES="node2 node3" "${SCRIPT_DIR}/config-use-bind-address-6"

ACTIVE_NODES="node1 node3" setup default

# Verify crash log of node3.

# TODO: Add new test that verifies downloading on machines with both
# ipv4 and ipv6. Need to add another machine.

verify_completed node3 test_h6 "verifying it works with http6 tracker over ipv4"
verify_completed node3 test_u6 "verifying it works with udp6 tracker over ipv4"

verify_incompleted node3 test_h4 "verifying it does not work with http4 tracker over ipv4"
verify_incompleted node3 test_u4 "verifying it does not work with udp4 tracker over ipv4"

exit_test
