#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

echo "running bind_v4"

clean_all

# Add v6 bind.
NODES="node2 node3" "${SCRIPT_DIR}/config-use-bind-address"

ACTIVE_NODES="node1 node2" setup default

# Verify crash log of node3.

# TODO: Add new test that verifies downloading on machines with both
# ipv4 and ipv6. Need to add another machine.

verify_completed node2 test_h6 "verifying it does not work with http6 tracker over ipv4"
verify_completed node2 test_u6 "verifying it does not work with udp6 tracker over ipv4"

verify_incompleted node2 test_h4 "verifying it works with http4 tracker over ipv4"
verify_incompleted node2 test_u4 "verifying it works with udp4 tracker over ipv4"

exit_test
