#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

# TODO: Rename to bind_ip_v4v6only

echo "running bind_add_v4v6only"

clean_all

# TODO: Only use one node in test? Or make sure node3 fails all to test block-connect?

# If accept...

"${SCRIPT_DIR}/config-set-block-connect" node1
"${SCRIPT_DIR}/config-set-block-accept" node2
"${SCRIPT_DIR}/config-set-block-accept" node3
"${SCRIPT_DIR}/config-set-block-connect" node3

# TODO: Make node2 use default address, node3 bind.
# TODO: Add support for looking up address by name, 
# TODO: Pass hostname to bind, allow us to refresh it.
# TODO: Test fails on invalid address.

"${SCRIPT_DIR}/config-bind-clear" node2
"${SCRIPT_DIR}/config-bind-add" node2 v4 100 0.0.0.0 v4only
#"${SCRIPT_DIR}/config-bind-add" node2 :: v6only

"${SCRIPT_DIR}/config-bind-clear" node3
"${SCRIPT_DIR}/config-bind-add" node3 v4 100 ipv4.1 v4only
#"${SCRIPT_DIR}/config-bind-add" node3 ipv6.2 v6only

setup pair_v4v6

# TODO: Need to also add test for incoming, requires a new clean test.

# No filtering on node 2, rtorrent is responsible for separating traffic.

# node2 tests outgoing bind v4 on if1, v6 on if2
# - v4 should work on if1
# - v6 should work on if2
# - v6 should not work on if1
# - v4 should not work on if2

verify_completed   node2 test_h4_if1 "bind ipv4 any address with v4only"
verify_completed   node2 test_u4_if1 "bind ipv4 any address with v4only"
verify_incompleted node2 test_h6_if1 "bind ipv4 any address with v4only"
verify_incompleted node2 test_u6_if1 "bind ipv4 any address with v4only"

verify_incompleted node2 test_h4_if2 "bind ipv6 any address with v6only"
verify_incompleted node2 test_u4_if2 "bind ipv6 any address with v6only"
verify_completed   node2 test_h6_if2 "bind ipv6 any address with v6only"
verify_completed   node2 test_u6_if2 "bind ipv6 any address with v6only"

verify_completed   node3 test_h4_if1 "bind ipv4 specific address with v4only"
verify_completed   node3 test_u4_if1 "bind ipv4 specific address with v4only"
verify_incompleted node3 test_h6_if1 "bind ipv4 specific address with v4only"
verify_incompleted node3 test_u6_if1 "bind ipv4 specific address with v4only"

verify_incompleted node3 test_h4_if2 "bind ipv6 specific address with v6only"
verify_incompleted node3 test_u4_if2 "bind ipv6 specific address with v6only"
verify_completed   node3 test_h6_if2 "bind ipv6 specific address with v6only"
verify_completed   node3 test_u6_if2 "bind ipv6 specific address with v6only"

exit_test
