#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

echo "running default"

clean_all
setup default

verify_completed   node2 test_h4_if1 "verifying it works with http4 tracker over ipv4"
verify_completed   node2 test_u4_if1 "verifying it works with udp4  tracker over ipv4"
verify_completed   node3 test_h6_if1 "verifying it works with http6 tracker over ipv6"
verify_completed   node3 test_u6_if1 "verifying it works with udp6  tracker over ipv6"

verify_completed   node2 test_h4_if2 "verifying it works with http4 tracker over ipv4/6"
verify_completed   node2 test_u4_if2 "verifying it works with udp4  tracker over ipv4/6"
verify_completed   node2 test_h6_if2 "verifying it works with http6 tracker over ipv4/6"
verify_completed   node2 test_u6_if2 "verifying it works with udp6  tracker over ipv4/6"
verify_completed   node3 test_h4_if2 "verifying it works with http4 tracker over ipv4/6"
verify_completed   node3 test_u4_if2 "verifying it works with udp4  tracker over ipv4/6"
verify_completed   node3 test_h6_if2 "verifying it works with http6 tracker over ipv4/6"
verify_completed   node3 test_u6_if2 "verifying it works with udp6  tracker over ipv4/6"

verify_incompleted node2 test_h6_if1 "verifying it does not work with http6 tracker over ipv4"
verify_incompleted node2 test_u6_if1 "verifying it does not work with udp6  tracker over ipv4"
verify_incompleted node3 test_h4_if1 "verifying it does not work with http4 tracker over ipv6"
verify_incompleted node3 test_u4_if1 "verifying it does not work with udp4  tracker over ipv6"

exit_test
