#!/usr/bin/env bash

source "$(dirname ${BASH_SOURCE[0]})/../scripts/include/call"
source "$(dirname ${BASH_SOURCE[0]})/../scripts/include/test"

echo "running default"

clean_all
setup if1p1_if2v4v6

verify_completed   node2 test_h4_if1 "http4 tracker with v4only"
verify_completed   node2 test_u4_if1 "udp4  tracker with v4only"
verify_incompleted node2 test_h6_if1 "http6 tracker with v4only"
verify_incompleted node2 test_u6_if1 "udp6  tracker with v4only"
verify_completed   node2 test_h4_if2 "http4 tracker with v4v6"
verify_completed   node2 test_u4_if2 "udp4  tracker with v4v6"
verify_completed   node2 test_h6_if2 "http6 tracker with v4v6"
verify_completed   node2 test_u6_if2 "udp6  tracker with v4v6"

verify_incompleted node3 test_h4_if1 "http4 tracker with v6only"
verify_incompleted node3 test_u4_if1 "udp4  tracker with v6only"
verify_completed   node3 test_h6_if1 "http6 tracker with v6only"
verify_completed   node3 test_u6_if1 "udp6  tracker with v6only"
verify_completed   node3 test_h4_if2 "http4 tracker with v4v6"
verify_completed   node3 test_u4_if2 "udp4  tracker with v4v6"
verify_completed   node3 test_h6_if2 "http6 tracker with v4v6"
verify_completed   node3 test_u6_if2 "udp6  tracker with v4v6"

exit_test
