#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"

echo "running default"

clean_all
setup default_v4

verify_completed node2 test_h4 "verifying it works with http4 tracker over ipv4"
verify_completed node2 test_u4 "verifying it works with udp4 tracker over ipv4"

verify_incompleted node3 test_h6 "verifying it does not work with http6 tracker over ipv6"
verify_incompleted node3 test_u6 "verifying it does not work with udp6 tracker over ipv6"
verify_incompleted node2 test_h6 "verifying it does not work with http6 tracker over ipv4"
verify_incompleted node2 test_u6 "verifying it does not work with udp6 tracker over ipv4"
verify_incompleted node3 test_h4 "verifying it does not work with http4 tracker over ipv6"
verify_incompleted node3 test_u4 "verifying it does not work with udp4 tracker over ipv6"

exit_test
