#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"

set -e

# Check if we have the right init.

clean_all() {
    echo "clean all"

    #"${SCRIPT_DIR}/test-delete-all" &> /dev/null; sleep 1
    "${SCRIPT_DIR}/test-delete-all"; sleep 1
    "${SCRIPT_DIR}/stop-rtorrent"; sleep 1

    "${SCRIPT_DIR}/config-clear"
}

start_nodes() {
    echo "starting clients"
    "${SCRIPT_DIR}/start-rtorrent"

    echo "waiting for clients"
    wait_for_nodes "is-client-active"
}

create_torrents() {
    "${SCRIPT_DIR}/test-create-all"

    local torrent=

    for torrent in test_h4 test_h6 test_u4 test_u6; do
        wait_for_nodes is-loaded ${torrent}
        echo "${torrent}: loaded"
    done
}

echo "starting 'default'"

clean_all
start_nodes
create_torrents

echo "done"
