#!/bin/bash

DEBUG=1

NODES=(`ls data/ | grep "^node"`)
CLIENT="./scripts/xmlrpc2scgi.py"

call_remote_nodes() {
    for NODE in ${NODES[@]}; do
        echo "$NODE:"
        ./scripts/ssh $NODE $@
    done
}

call_rpc() {
    FORWARD_PORT=`cat ./data/${NODE}/metadata/forward.5001`

    if [ -z ${FORWARD_PORT} ]; then
        echo "Could not find forward port for ${NODE}"
        exit -1
    fi

    NODE_URL="scgi://localhost:${FORWARD_PORT}"

    CALL_CMD="$CLIENT -s $NODE_URL $@"

    #echo $CALL_CMD

    $CALL_CMD | awk -f ./scripts/include/${AWK_FILE}.awk
}

call_rpc_nodes() {
    for NODE in ${NODES[@]}; do
        echo "${NODE}:"
        call_rpc $@
    done
}
