#!/bin/bash

source ./scripts/include/nodes

DEBUG=1

CLIENT="./scripts/xmlrpc2scgi.py"

call_rpc() {
    FORWARD_PORT=`cat ./data/${NODE}/metadata/forward.5001`

    if [ -z ${FORWARD_PORT} ]; then
        echo "Could not find forward port for ${NODE}"
        exit -1
    fi

    NODE_URL="scgi://localhost:${FORWARD_PORT}"

    CALL_CMD="$CLIENT -s $NODE_URL $@"

    echo $CALL_CMD

    $CALL_CMD | awk -f ./scripts/include/${AWK_FILE}.awk
}

call_rpc_nodes() {
    for NODE in ${NODES[@]}; do
        echo "${NODE}:"
        call_rpc $@
    done
}
