#!/bin/bash

export CXX="${USE_CXX:?No C++ compiler specified.}"
export CXXFLAGS="-Wno-error=strict-aliasing"
export MAKEFLAGS="-j 8"

RTORRENT_CONF="--with-xmlrpc-c"

if [ "${DO_CONFIGURE}" != "yes" ]; then
    cd /data/local/libtorrent && ./autogen.sh && ./configure || exit 1
    cd /data/local/rtorrent   && ./autogen.sh && ./configure ${RTORRENT_CONF} || exit 1
fi

if [ "${SKIP_LIBTORRENT}" != "yes" ]; then
    cd /data/local/libtorrent
    make && sudo make install || exit 1
fi

if [ "${SKIP_RTORRENT}" != "yes" ]; then
    cd /data/local/rtorrent
    make && sudo make install || exit 1
fi

