#!/bin/bash

export CXX="g++-4.8"
export CXXFLAGS="-Wno-error=strict-aliasing"
export MAKEFLAGS="-j 8"

RTORRENT_CONF="--with-xmlrpc-c"

cd /data/local/libtorrent
[ "${SKIP_LIBTORRENT}" != "yes" ] && (./autogen.sh && ./configure && make tags && make && sudo make install || exit 1)

cd /data/local/rtorrent
./autogen.sh && ./configure ${RTORRENT_CONF} && make tags && make && sudo make install || exit 1
