#!/bin/bash

source /data/scripts/metadata.source
set -e

sudo ip -4 addr flush dev ${PRIVATE_DEV_2}
sudo ip -4 addr add $1 dev ${PRIVATE_DEV_2}

ip -4 addr show dev ${PRIVATE_DEV_2} permanent primary | sed -n 's_^.*inet \([0-9.]*\)/\([0-9]*\).*$_\1_p' > "${METADATA}/ipv4.2.address"
ip -4 addr show dev ${PRIVATE_DEV_2} permanent primary | sed -n 's_^.*inet \([0-9.]*\)/\([0-9]*\).*$_\2_p' > "${METADATA}/ipv4.2.prefix"

touch "${METADATA}/ipv4.2.up"
rm "${METADATA}/ipv4.2.down" &> /dev/null || true
