#!/bin/bash

source /usr/local/bin/metadata.source
set -e

sudo ip -4 addr flush dev ${PRIVATE_DEV_1}
sudo ip -4 addr add $1 dev ${PRIVATE_DEV_1}

ip -4 addr show dev ${PRIVATE_DEV_1} permanent primary | sed -n 's_^.*inet \([0-9.]*\)/\([0-9]*\).*$_\1_p' > "${METADATA}/ipv4.1.address"
ip -4 addr show dev ${PRIVATE_DEV_1} permanent primary | sed -n 's_^.*inet \([0-9.]*\)/\([0-9]*\).*$_\2_p' > "${METADATA}/ipv4.1.prefix"

touch "${METADATA}/ipv4.1.up"
rm "${METADATA}/ipv4.1.down" &> /dev/null || true
