#!/bin/bash

DATA_FILENAME=${1:?no filename provided}
DATA_PATH="/data/shared/torrents/${DATA_FILENAME}"

DATA_COUNT=${DATA_COUNT:=5}

openssl rand $(( DATA_COUNT * 1000000 )) > "${DATA_PATH}"

IPV4_1_TRACKER=`cat /data/local/metadata/ipv4.1.address`
IPV6_1_TRACKER=`cat /data/local/metadata/ipv6.1.address`
IPV4_2_TRACKER=`cat /data/local/metadata/ipv4.2.address`
IPV6_2_TRACKER=`cat /data/local/metadata/ipv6.2.address`

USE_IF1=${USE_IF1:=yes}
USE_IF2=${USE_IF2:=no}
USE_IPV4=${USE_IPV4:=yes}
USE_IPV6=${USE_IPV6:=no}

USE_HTTP_TRACKER=${USE_HTTP_TRACKER:=yes}
USE_UDP_TRACKER=${USE_UDP_TRACKER:=no}

if [ "${USE_HTTP_TRACKER}" == "yes" ]; then
    if [ "${USE_IPV4}" == "yes" ]; then
        [ "${USE_IF1}" == "yes" ] && ANNOUNCE_URLS+=",http://${IPV4_1_TRACKER}:6969/announce"
        [ "${USE_IF2}" == "yes" ] && ANNOUNCE_URLS+=",http://${IPV4_2_TRACKER}:6969/announce"
    fi

    if [ "$USE_IPV6" == "yes" ]; then
        [ "${USE_IF1}" == "yes" ] && ANNOUNCE_URLS+=",http://[${IPV6_1_TRACKER}]:6969/announce"
        [ "${USE_IF2}" == "yes" ] && ANNOUNCE_URLS+=",http://[${IPV6_2_TRACKER}]:6969/announce"
    fi
fi

if [ "${USE_UDP_TRACKER}" == "yes" ]; then
    if [ "${USE_IPV4}" == "yes" ]; then
        [ "${USE_IF1}" == "yes" ] && ANNOUNCE_URLS+=",udp://${IPV4_1_TRACKER}:6969"
        [ "${USE_IF2}" == "yes" ] && ANNOUNCE_URLS+=",udp://${IPV4_2_TRACKER}:6969"
    fi

    if [ "${USE_IPV6}" == "yes" ]; then
        [ "${USE_IF1}" == "yes" ] && ANNOUNCE_URLS+=",udp://[${IPV6_1_TRACKER}]:6969"
        [ "${USE_IF2}" == "yes" ] && ANNOUNCE_URLS+=",udp://[${IPV6_2_TRACKER}]:6969"
    fi
fi

ANNOUNCE_URLS=`echo ${ANNOUNCE_URLS} | sed -n 's/^,//p'`

if ! type mktorrent; then
    echo "Could not find 'mktorrent'."
    exit -1
fi

mktorrent -v -p -a ${ANNOUNCE_URLS} -o ${DATA_PATH}.torrent ${DATA_PATH}
