#!/bin/bash

export CXX="g++-4.8"
export CXXFLAGS="-Wno-error=strict-aliasing"
export MAKEFLAGS="-j 8"

RTORRENT_CONF="--with-xmlrpc-c"

if [ "${SKIP_LIBTORRENT}" != "yes" ]; then
    cd /data/local/libtorrent
    make && sudo make install || exit 1
fi

if [ "${SKIP_RTORRENT}" != "yes" ]; then
    cd /data/local/rtorrent
    make && sudo make install || exit 1
fi
