#!/bin/bash

export CXX="g++-4.8"
export CXXFLAGS="-Wno-error=strict-aliasing"

RTORRENT_CONF="--with-xmlrpc-c"

cd /data/local/libtorrent
./autogen.sh && ./configure && make && sudo make install || exit 1

cd /data/local/rtorrent
./autogen.sh && ./configure ${RTORRENT_CONF} && make && sudo make install || exit 1
