nodes:

  - name: builder
    primary: true
    builder: true
    cpus: 8
    memory: 3072
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.10
      ipv6: fd01::10
    - network: rnet2
      ipv4: 10.0.4.10
      ipv6: fd02::10

  - name: node1
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18601
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.11
      ipv6: fd01::11
    - network: rnet2
      ipv4: 10.0.4.11
      ipv6: fd02::11

  - name: node2
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18602
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.12
      ipv6: fd01::12
    - network: rnet2
      ipv4: 10.0.4.12
      ipv6: fd02::12

  - name: node3
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18603
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.13
      ipv6: fd01::13
    - network: rnet2
      ipv4: 10.0.4.13
      ipv6: fd02::13

  - name: node4
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18604
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.14
      ipv6: fd01::14
    - network: rnet2
      ipv4: 10.0.4.14
      ipv6: fd02::14

  - name: node5
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18605
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.15
      ipv6: fd01::15
    - network: rnet2
      ipv4: 10.0.4.15
      ipv6: fd02::15
