nodes:

  - hostname: builder
    primary: true
    builder: true
    cpus: 8
    memory: 2048
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.10
      ipv6: fdcc::10
    - network: rnet2
      ipv4: 10.0.4.10
      ipv6: fddd::10

  - hostname: node1
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18601
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.11
      ipv6: fdcc::11
    - network: rnet2
      ipv4: 10.0.4.11
      ipv6: fddd::11

  - hostname: node2
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18602
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.12
      ipv6: fdcc::12
    - network: rnet2
      ipv4: 10.0.4.12
      ipv6: fddd::12

  - hostname: node3
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18603
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.13
      ipv6: fdcc::13
    - network: rnet2
      ipv4: 10.0.4.13
      ipv6: fddd::13
