nodes:

  - hostname: builder
    primary: true
    builder: true
    cpus: 8
    memory: 3072
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.10
      ipv6: fdcc::10
    - network: rnet2
      ipv4: 10.0.4.10
      ipv6: fddd::10

  - hostname: node1
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18601
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.11
      ipv6: fdcc::11
    - network: rnet2
      ipv4: 10.0.4.11
      ipv6: fddd::11

  - hostname: node2
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18602
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.12
      ipv6: fdcc::12
    - network: rnet2
      ipv4: 10.0.4.12
      ipv6: fddd::12

  - hostname: node3
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18603
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.13
      ipv6: fdcc::13
    - network: rnet2
      ipv4: 10.0.4.13
      ipv6: fddd::13

  - hostname: node4
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18604
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.14
      ipv6: fdcc::14
    - network: rnet2
      ipv4: 10.0.4.14
      ipv6: fddd::14

  - hostname: node5
    cpus: 1
    memory: 512
    forward:
    - guest: 5001
      host: 18605
    interfaces:
    - network: rnet1
      ipv4: 10.0.3.15
      ipv6: fdcc::15
    - network: rnet2
      ipv4: 10.0.4.15
      ipv6: fddd::15
