nodes:

  - hostname: builder
    primary: true
    builder: true
    cpus: 8
    memory: 2048
    ipv6: 10

  - hostname: node1
    ipv6: 11
    forward:
    - guest: 5001
      host: 18601

  - hostname: node2
    ipv6: 12
    forward:
    - guest: 5001
      host: 18602
