nodes:

  - hostname: builder
    primary: true
    builder: true
    cpus: 8
    memory: 2048
    ipv4: 10
    ipv6: 10

  - hostname: node1
    ipv4: 11
    ipv6: 11
    forward:
    - guest: 5001
      host: 18601

  - hostname: node2
    ipv4: 12
    ipv6: 12
    forward:
    - guest: 5001
      host: 18602

  - hostname: node3
    ipv4: 13
    ipv6: 13
    forward:
    - guest: 5001
      host: 18603
