#!/bin/bash

export DATA_FILENAME=$1

source `dirname ${BASH_SOURCE[0]}`/include/call
source `dirname ${BASH_SOURCE[0]}`/include/torrent

# TODO: Check that filename and torrent exists.

vagrant ssh ${SEED_NODE} -c "cp -r '${DATA_VM_PATH}' '${DATA_VM_TORRENTS}'"
ln ${DATA_HOST_PATH}.torrent ${DATA_HOST_WATCH}
