#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"

cd "${DATA_DIR}/builder/"

[[ -d "libtorrent" ]] || git clone git@github.com:rakshasa/libtorrent
[[ -d "rtorrent" ]] || git clone git@github.com:rakshasa/rtorrent
[[ -d "opentracker" ]] || git clone git@github.com:rakshasa/opentracker
