#!/usr/bin/env bash
#
# Returns an empty string any state source is missing.

source "`dirname ${BASH_SOURCE[0]}`/include/init"
source "`dirname ${BASH_SOURCE[0]}`/include/repo"

cat "${DATA_DIR}/current-libtorrent-conf" && repo_state_blob "${GIT_LIBTORRENT}" | md5sum
