#!/bin/bash

source ./scripts/sources/git

LIBTORRENT_GIT_BRANCH=${1:?no libtorrent git branch provided}
RTORRENT_GIT_BRANCH=${2:?no rtorrent git branch provided}

(cd "$GIT_LIBTORRENT" && git checkout "${LIBTORRENT_GIT_BRANCH}" && git pull)
(cd "$GIT_RTORRENT" && git checkout "${RTORRENT_GIT_BRANCH}" && git pull)

vagrant ssh builder -c "/home/vagrant/build-rtorrent"
