#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"

OLD_HASH="$(<"${DATA_DIR}/current-state-libtorrent")"
CURRENT_HASH="$("${SCRIPT_DIR}/build-state-libtorrent" 2> /dev/null)"

[[ -n "${OLD_HASH}" ]] && [[ "${OLD_HASH}" == "${CURRENT_HASH}" ]]
