#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/include/call"

"${SCRIPT_DIR}/ssh" builder 'cd /data/local/libtorrent && make tags' || exit 1
"${SCRIPT_DIR}/ssh" builder 'cd /data/local/rtorrent && make tags' || exit 1

IFS=$'\n'

for i in `find "${GIT_LIBTORRENT}" "${GIT_RTORRENT}" -name TAGS`; do
    echo "Changing base path of directory tags in '${i}'"
    sed -e "s:^${i/%TAGS/}:./:" "$i" > "$i.new"
    mv "$i.new" "$i"
done
