#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"
source "${BASH_SOURCE[0]%/*}/include/call-ssh"

call_ssh_node builder 'cd /data/local/libtorrent && make tags'
call_ssh_node builder 'cd /data/local/rtorrent && make tags'

IFS=$'\n'

for repo in 'libtorrent' 'rtorrent'; do
  (
    cd "${DATA_DIR}/builder/${repo}"

    for i in `find . -name TAGS`; do
      echo "Changing base path of directory tags in '${i}'"

      path="${i/%TAGS/}"
      sed -e "s:^/data/local/${repo}/${path/.\//}:./:" "$i" > "$i.new"

      mv "$i.new" "$i"
    done
  )
done
