#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/include/call"

rm "${DATA_DIR}/builder/libtorrent/test/test-suite.log"
rm "${DATA_DIR}/builder/rtorrent/test/test-suite.log"

"${SCRIPT_DIR}/ssh" builder "TEST_NAME=${TEST_NAME} check-libtorrent" || cat "${DATA_DIR}/builder/libtorrent/test/test-suite.log" || exit 1
"${SCRIPT_DIR}/ssh" builder "TEST_NAME=${TEST_NAME} check-rtorrent" || cat "${DATA_DIR}/builder/rtorrent/test/test-suite.log" || exit 1
