#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"
source "${BASH_SOURCE[0]%/*}/include/call-ssh"

echo "tracker stopping"
call_ssh_node builder sudo service opentracker stop &> /dev/null || :
echo "tracker building"
call_ssh_node builder IPV4_ONLY=${IPV4_ONLY} build-tracker
echo "tracker starting"
call_ssh_node builder sudo service opentracker start
echo "tracker started"
