#!/bin/bash

source ./scripts/sources/git

GIT_BRANCH=${1:?no git branch provided}

(cd "$GIT_LIBTORRENT" && git checkout "${GIT_BRANCH}" && git pull)
(cd "$GIT_RTORRENT" && git checkout "${GIT_BRANCH}" && git pull)

vagrant ssh builder -c "/home/vagrant/build-rtorrent"
