#!/bin/bash

source "`dirname ${BASH_SOURCE[0]}`/include/call"

echo "tracker stopping"
"${SCRIPT_DIR}/ssh" builder "sudo service opentracker stop" &> /dev/null || :
echo "tracker building"
"${SCRIPT_DIR}/ssh" builder "IPV4_ONLY=${IPV4_ONLY} build-tracker"
echo "tracker starting"
"${SCRIPT_DIR}/ssh" builder "sudo service opentracker start"
echo "tracker started"
