#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"

USE_CONFIG="${1:?Missing build config argument.}"

mkdir "${DATA_DIR}" &> /dev/null || :
echo "${USE_CONFIG}" > "${DATA_DIR}/current-config"
