#!/bin/bash

source `dirname ${BASH_SOURCE[0]}`/include/call

CALL_NODE="${1:?Missing node argument.}"
COMMAND="${2:?Missing command argument.}"
TARGET="${TARGET:-s/}"

CALL_NODE="${CALL_NODE}" call_rpc "${COMMAND}" "${TARGET}" ${@:3}
