#!/bin/bash

source `dirname ${BASH_SOURCE[0]}`/include/call

NODE=${1:?Target node not given.}
BIND_NAME=${2:?Bind name not given.}
PRIORITY=${3:?Priority not given.}
NODE_IP=${4:?Node ip address not given.}
OPTIONS=""

case "${NODE_IP}" in
    ipv[46].[12])
        NODE_IP=`cat ${DATA_DIR}/${NODE}/metadata/${NODE_IP}.address`
        ;;
esac

for o in ${@:5}; do
    OPTIONS+=", ${o}"
done

echo "${NODE}: ${NODE_IP}${OPTIONS}"

extra_rc_command_padding "network.bind"
echo -e "network.bind.add = ${BIND_NAME}, ${PRIORITY}, ${NODE_IP}${OPTIONS}" >> "${DATA_DIR}/${NODE}/config/extra.rc"
