#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"

NODE=${1:?Target node not given.}

extra_rc_command_padding "network.bind"
echo -e "network.bind.clear =" >> "${DATA_DIR}/${NODE}/config/extra.rc"
