#!/usr/bin/env bash

source `dirname ${BASH_SOURCE[0]}`/include/call

NODE=${1:?Target node not given.}

echo "${NODE}: enable port randomize"

echo -e "\nnetwork.port.randomize.set = true" >> "${DATA_DIR}/${NODE}/config/extra.rc"
