#!/usr/bin/env bash

source `dirname ${BASH_SOURCE[0]}`/include/call

NODE=${1:?Target node not given.}
PORT_BEGIN=${2:?Beginning port number not given.}
PORT_END=${3:?Ending port number not given.}

echo "${NODE}: port range ${PORT_BEGIN}-${PORT_END}"

echo -e "\nnetwork.port_range.set = ${PORT_BEGIN}-${PORT_END}" >> "${DATA_DIR}/${NODE}/config/extra.rc"
