#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"

NODE=${1:?Target node not given.}

echo "${NODE}: block connect"

echo -e "\nnetwork.block.connect.set = true" >> "${DATA_DIR}/${NODE}/config/extra.rc"
