#!/usr/bin/env bash

source `dirname ${BASH_SOURCE[0]}`/include/call

for NODE in 'shared' ${NODES[@]}; do
    echo "$NODE: initializing extra.rc"
    rm "${DATA_DIR}/${NODE}/config/extra.rc" || true
    cat > "${DATA_DIR}/${NODE}/config/extra.rc" <<EOF
# Extra options for '${NODE}'.

print = "Loading extra options for '${NODE}'."
EOF
done
