#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"

NODE=${1:?Target node not given.}

echo "${NODE}: disable port randomize"

echo -e "\nnetwork.port.randomize.set = false" >> "${DATA_DIR}/${NODE}/config/extra.rc"
