#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"
source "${BASH_SOURCE[0]%/*}/include/call-ssh"

# Glibc crashes if you have multiple nameservers and either ipv4 or
# ipv6 nameservers are not routeable.
#
# Some resolvers don't handle multiple nameservers properly, pass
# argument to reorder the nameservers.

case "${1}" in
  builder)
    CLEAR_TARGET="base"
    RESOLV_TARGET="head"
    ;;
  internet | default)
    CLEAR_TARGET="head"
    RESOLV_TARGET="base"
    ;;
  *)
    echo "invalid argument: '${1}'"
    exit 1
    ;;
esac

NAMESERVER_IF1V4=$(<"${DATA_DIR}/builder/metadata/ipv4.1.address")
NAMESERVER_IF1V6=$(<"${DATA_DIR}/builder/metadata/ipv6.1.address")

call_ssh_parallel "/data/scripts/scripts/ip-dns-resolver" "${CLEAR_TARGET}" "${RESOLV_TARGET}" "${NAMESERVER_IF1V4}" "${NAMESERVER_IF1V6}"
