#!/bin/bash

source `dirname ${BASH_SOURCE[0]}`/include/call

CONFIG_NAME="${1:?Missing config name argument.}"

"${SCRIPT_DIR}/ssh" builder "sudo rm /etc/maradns/mararc"
"${SCRIPT_DIR}/ssh" builder "sudo ln -s '/etc/maradns/mararc.${CONFIG_NAME}' /etc/maradns/mararc"
"${SCRIPT_DIR}/ssh" builder "sudo service maradns restart"
