#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"
source "${BASH_SOURCE[0]%/*}/include/call-args"
source "${BASH_SOURCE[0]%/*}/include/call-rpc"
source "${BASH_SOURCE[0]%/*}/include/call-test"

test_is_node_check() {
  local node="${1:?Target node not given.}"

  [[ -z "$(call_rpc_node "${node}" system.client_version)" ]]
}

test_is_node "${@}"
