#!/bin/bash

source `dirname ${BASH_SOURCE[0]}`/include/call

[ -z ${CALL_NODE} ] && CALL_NODE=${2:?Target node not given.}

INFO_HASH_RET=`${SCRIPT_DIR}/torrent-info-hash "$1"`
INFO_HASH=${INFO_HASH_RET:?Info hash not found.}

call_rpc d.complete "s/${INFO_HASH}"
