#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/call"

CALL_NODE="${1:?Target node not given.}"
RESULT="$(call_rpc d.multicall2 s/ main d.hash=)"

if [[ -z "${RESULT}" ]]; then
    [[ "${DEBUG}" == "1" ]] && >&2 echo "is-empty (true): '${RESULT}'"
    exit 0
else
    [[ "${DEBUG}" == "1" ]] && >&2 echo "is-empty (false): '${RESULT}'"
    exit 1
fi
