#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"
source "${BASH_SOURCE[0]%/*}/include/call-args"
source "${BASH_SOURCE[0]%/*}/include/call-rpc"
source "${BASH_SOURCE[0]%/*}/include/call-test"

test_is_node_check() {
  local node="${1:?Target node not given.}"
  local torrents=("${@:2}")
  local output=($(call_rpc_node "${node}" d.multicall2 s/ s/ d.name=))

  for match_name in "${torrents[@]}"; do
    local match_found=
    for output_name in "${output[@]}"; do
      [[ "${output_name}" =~ ^${match_name}$ ]] && match_found="${match_name}"
    done
    [[ -z "${match_found}" ]] || return 1
  done
}

test_is_node "${@}"
