#!/bin/bash

source `dirname ${BASH_SOURCE[0]}`/include/call

AWK_FILE='ls-torrents'

# Why d.complete and not d.is_complete.
call_rpc_awk_nodes d.multicall2 s/ main d.hash= d.is_open= d.is_active= d.complete= d.completed_chunks= d.size_chunks= d.up.rate= d.down.rate= d.name=
