#!/bin/bash

SCRIPT_PATH="${BASH_SOURCE[0]}"
SCRIPT_DIR=`dirname ${SCRIPT_PATH}`

TORRENT_DIR="/data/torrents"

source ${SCRIPT_DIR}/include/call

call_ssh_nodes_p "rm ${TORRENT_DIR}/${1}"

rm "./data/shared/torrents/${1}"
rm "./data/shared/torrents/${1}.torrent"
