#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"
source "${BASH_SOURCE[0]%/*}/include/call-ssh"

if getopts "s" opt; then
    call_ssh_sequential "start-rtorrent"
else
    call_ssh_parallel "start-rtorrent"
fi
