#!/usr/bin/env bash
#
# Compile with each of the different async dns resolvers, do make
# check and ci test default/bind/dns.
#
# Improve test naming in the results.

source "$(dirname ${BASH_SOURCE[0]})/include/init"
source "$(dirname ${BASH_SOURCE[0]})/include/test-unit"

test_dns() {
  test_unit "default"
  test_unit "dns_default"
  test_dns_resolver builder
  test_unit "dns_default"
  test_dns_resolver default
}

test_init "test-feature-dns"
test_dns_resolver default

test_begin "Default"
test_compile ""
test_has_features with-udns
test_dns

test_begin "Without UDNS"
test_compile "WITHOUT_UDNS=yes"
test_has_features without-udns
test_dns

test_begin "With UDNS"
test_compile "WITHOUT_UDNS=no"
test_has_features with-udns
test_dns

test_cleanup
