#!/bin/bash

source `dirname ${BASH_SOURCE[0]}`/include/call

TEST_TORRENTS="test_h4 test_h6 test_u4 test_u6"

for i in ${TEST_TORRENTS}; do
    ${SCRIPT_DIR}/deactivate-torrent $i
    ${SCRIPT_DIR}/rm-torrent $i
done
