#!/usr/bin/env bash

source `dirname ${BASH_SOURCE[0]}`/include/call

echo default
echo bind_port_simple
echo bind_port_randomize
echo bind_set_v4v6only
echo bind_add_v4v6only_accept
echo encryption_none
echo encryption_require
