#!/bin/bash

source `dirname ${BASH_SOURCE[0]}`/include/call

echo default
echo default_v4
echo default_v6
echo bind_v4
echo bind_v6
echo bind_port_simple
echo bind_port_randomize_v4
echo bind_port_randomize_v6
echo bind_add_v4v6only_accept
