#!/usr/bin/env bash

source `dirname ${BASH_SOURCE[0]}`/include/call

for i in $("${SCRIPT_DIR}/test-torrent-all"); do
    "${SCRIPT_DIR}/torrent-deactivate" $i &> /dev/null || :
    "${SCRIPT_DIR}/rm-torrent" $i &> /dev/null || :
done

for node in ${NODES}; do
    rm -f ${DATA_DIR}/${node}/session/*.torrent &> /dev/null || :
    rm -f ${DATA_DIR}/${node}/session/*.torrent.* &> /dev/null || :
    rm -f ${DATA_DIR}/${node}/session/rtorrent.{dht_cache,input_history} &> /dev/null || :
done
