#!/bin/bash

source `dirname ${BASH_SOURCE[0]}`/include/call

TEST_TORRENTS="test_h4 test_h6 test_u4 test_u6 test_h4_if2 test_h6_if2 test_u4_if2 test_u6_if2"

# Fails to delete multiple torrents with the same name.

for i in ${TEST_TORRENTS}; do
    "${SCRIPT_DIR}/deactivate-torrent" $i &> /dev/null || :
    "${SCRIPT_DIR}/rm-torrent" $i &> /dev/null || :
done
