#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"
source "${BASH_SOURCE[0]%/*}/include/call-ssh"

TORRENT_FILENAME="${1:?Missing torrent filename.}"

call_ssh_node "${SEED_NODE}" cp -r "${TORRENT_VM_SHARED_DIR}/*" "${TORRENT_VM_DIR}"

(rm "${DATA_HOST_WATCH}/${TORRENT_FILENAME}.torrent" || true) &> /dev/null
cp "${TORRENT_SHARED_DIR}/${TORRENT_FILENAME}.torrent" "${DATA_HOST_WATCH}"
