#!/bin/bash

source `dirname ${BASH_SOURCE[0]}`/include/call

"${SCRIPT_DIR}/ssh" builder "USE_HTTP_TRACKER=${USE_HTTP_TRACKER} USE_UDP_TRACKER=${USE_UDP_TRACKER} USE_IPV4=${USE_IPV4} USE_IPV6=${USE_IPV6} USE_IF1=${USE_IF1} USE_IF2=${USE_IF2} make-torrent" $@ || exit -1
