#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/init"
source "${BASH_SOURCE[0]%/*}/include/call-ssh"

node="${1:?Node or local not specified.}"
root_dir="${2:?Root directory not specified.}"
wildcard="${3:?Wildcard not specified.}"

if [[ "${node}" = "local" ]]; then
  (cd ${root_dir} && ls -1d ${wildcard})
else
  call_ssh_node "${node}" -- "(cd ${root_dir} && ls -1d ${wildcard})"
fi
