#!/usr/bin/env bash

export DATA_FILENAME="${1:?Missing torrent filename.}"

source "${BASH_SOURCE[0]%/*}/include/call"
source "${BASH_SOURCE[0]%/*}/include/torrent"

rm "${DATA_HOST_WATCH}/${DATA_FILENAME}.torrent"
