#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/include/call"

torrent_name="${1:?Torrent name not specified.}"
dst_dir="${2:?Destination directory not specified.}"

"${SCRIPT_DIR}/scp" -r "node-dl:/data/torrents/${torrent_name}" "${dst_dir}/"
