#!/bin/bash

SCRIPT_PATH="${BASH_SOURCE[0]}"
SCRIPT_DIR=`dirname ${SCRIPT_PATH}`

source ${SCRIPT_DIR}/include/git

find ${GIT_LIBTORRENT} ${GIT_RTORRENT} -name TAGS -exec rm {} \;

(cd ${GIT_LIBTORRENT} && ctags -eR)
(cd ${GIT_RTORRENT} && ctags -eR)
