#!/bin/bash

source /usr/local/bin/metadata.source
set -e

sudo ip -6 addr flush dev ${PRIVATE_DEV}
sudo ip -6 addr add ${METADATA_PRIVATE_IPV6} dev ${PRIVATE_DEV}

touch ${METADATA}/ipv6.up
rm ${METADATA}/ipv6.down &> /dev/null || true
