#!/bin/bash

source /usr/local/bin/metadata.source
set -e

sudo ip -4 addr flush dev ${PRIVATE_DEV}
sudo ip -4 addr add ${METADATA_PRIVATE_IPV4} dev ${PRIVATE_DEV}

touch ${METADATA}/ipv4.up
rm ${METADATA}/ipv4.down &> /dev/null || true
